language: java
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
  
# Travis calls `mvn install` automatically without tests
# https://docs.travis-ci.com/user/languages/java/#Dependency-Management
# -B - non-interactive, -V - show version
#install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test
  - mvn dependency:copy-dependencies
  - ls -la
