language: java
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
  
env:
  - DISTZIP=crawler-dev-${TRAVIS_BUILD_NUMBER}.zip
  
# Travis calls `mvn install` automatically without tests
# https://docs.travis-ci.com/user/languages/java/#Dependency-Management
# -B - non-interactive, -V - show version
#install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test
  - mvn dependency:copy-dependencies -DoutputDirectory=$PWD/bin
  - zip $DISTZIP bin/*
  - echo $DISTZIP

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: $DISTZIP
  skip_cleanup: true
