language: java
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
  
# Travis calls `mvn install` automatically
# https://docs.travis-ci.com/user/languages/java/#Dependency-Management
#install:
#  - mvn install

script:
  - mvn dependency:copy-dependencies